export { default as Header } from './Header/Header.jsx';
export { default as Footer } from './Footer/Footer.jsx';
export { default as HeaderSection } from './HeaderSection/HeaderSection.jsx';
export { default as CarCard } from './CarCard/CarCard.jsx';
export { default as NewsLetter } from './NewsLetter/NewsLetter.jsx';
export { default as AccordeonContainer } from './AccordeonContainer/AccordeonContainer.jsx';
export { default as Banner } from './Banner/Banner.jsx';
export { default as Slider } from './Slider/Slider.jsx';
export { default as SearchBar } from './SearchBar/SearchBar.jsx';